name: Generate Licenses

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  metrics:
    name: "Generate License Graph"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout nexus-ai repository
        uses: actions/checkout@v4
        with:
          repository: Yungshween/nexus-ai
          token: ${{ secrets.NEXUS_PAT }}
          path: nexus-ai

      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.licenses.ratio.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          user: Yungshween
          repo: nexus-ai
          template: repository
          plugin_licenses: yes
          plugin_licenses_setup: |
            bash -c '
            if [ -f nexus-ai/backend/pyproject.toml ]; then
              cd nexus-ai/backend
              python -m pip install --upgrade pip
              pip install uv
              pip install -e .
            fi
            if [ -f nexus-ai/frontend/package.json ]; then
              cd nexus-ai/frontend
              npm ci
              npm run build
            fi'
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          retries: 3
          optimize: svg
          verify: yes
