name: Generate Metrics

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  metrics:
    name: "Generate All Metrics"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.NEXUS_PAT }}
          repository: Yungshween/nexus-ai
          path: nexus-ai

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          pip install .
        working-directory: backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure this matches your local development version

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.licenses.ratio.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          user: Yungshween
          repo: nexus-ai
          template: repository
          plugin_licenses: yes
          plugin_licenses_setup: |
            bash -c '
            if [ -f backend/pyproject.toml ]; then
              cd backend
              python -m pip install --upgrade pip
              pip install uv
              uv pip install . || true
            fi
            if [ -f frontend/package.json ]; then
              cd frontend
              npm ci || true
            fi'
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          retries: 3
          optimize: svg
          verify: yes
