name: Metrics

on:
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  repository-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: docs/assets/images/metrics/metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          config_timezone: America/New_York
          plugin_introduction: yes
          plugin_introduction_title: yes

  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Languages Analysis
        uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 400
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

  activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Activity Analysis
        uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_timestamps: yes

  traffic:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Traffic Analysis
        uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_traffic: yes

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Development Habits
        uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

  contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repository Contributors
        uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.contributors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_contributors: yes
          plugin_contributors_head: main
          plugin_contributors_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]

  repository-license:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: License Analysis
        uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.licenses.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          template: repository
          base: ""
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
          plugin_licenses_setup: bash -c '[[ -f pyproject.toml ]] && pip install -e . || true'