name: Metrics

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  metrics:
    name: "Generate All Metrics"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Base metrics
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          base: header, activity, community, repositories
          filename: docs/assets/images/metrics/github-metrics.svg
          token: ${{ secrets.NEXUS_PAT }}
          config_timezone: America/New_York
          retries: 3
          optimize: svg
          verify: yes

      # Languages
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.languages.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 400
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      # Projects
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.projects.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          plugin_projects: yes
          plugin_projects_limit: 4

      # LeetCode
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.leetcode.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: yungshween

      # Star Lists
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.starlists.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8

      # Topics
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.topics.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15

      # Topic Icons
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.topics.icons.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      # WakaTime
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os

      # RSS Feed
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: http://export.arxiv.org/rss/q-fin 
          plugin_rss_limit: 8

      # Repository License
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Yungshween/nexus-ai
          token: ${{ secrets.NEXUS_PAT }}
          path: main

      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.licenses.ratio.svg
          token: ${{ secrets.NEXUS_PAT }}
          base: ""
          repo: Yungshween/nexus-ai
          plugin_licenses: yes
          plugin_licenses_setup: |
            bash -c '
            if [ -f backend/pyproject.toml ]; then
              python -m pip install --upgrade pip
              pip install uv
              uv pip install . || true
            fi
            if [ -f frontend/package.json ]; then
              npm ci || true
            fi'
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          retries: 3
          optimize: svg
          verify: yes

      # Calendar
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
