name: Metrics

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  metrics:
    name: "Generate Metrics"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          base: header, activity, community, repositories
          filename: docs/assets/images/metrics/github-metrics.svg  # Updated filename to match your README
          token: ${{ secrets.METRICS_TOKEN }}
          # Additional recommended configurations
          config_timezone: America/New_York  # Adjust to your timezone
          retries: 3
          optimize: svg
          verify: yes
          
  languages:
    name: "Generate Languages"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 400
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
  projects:
    name: "Generate Projects"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_projects: yes
          plugin_projects_limit: 4
          
  leetcode:
    name: "LeetCode Stats"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_leetcode: yes
          plugin_leetcode_user: yungshween
          
  starlists:
    name: "Star Lists"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.starlists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_languages: yes
          
  repositories:
    name: "Repositories"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_featured: 1
          
  topics:
    name: "Topics"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15

  icons:
    name: "Icons"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.topics.icons.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

  repository-license:
    name: "Licenses with open-source ratio graphs"
    runs-on: ubuntu-latest
    permissions:
    contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Add checkout step
              
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.licenses.ratio.svg  # Updated path to match your README
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: Yungshween/nexus-ai
          plugin_licenses: yes
          plugin_licenses_setup: |
            bash -c '
            if [ -f pyproject.toml ]; then
              python -m pip install --upgrade pip
              pip install uv
              uv pip install -r requirements.txt || true
            fi
            if [ -f package.json ]; then
              npm ci || true
            fi'
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
            # Additional recommended configurations
          retries: 3
          retry_delay: 300
          optimize: svg
          verify: yes

  repository-calendar:
    name: "Full-year calendar"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
