name: Metrics

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          base: header, activity, community, repositories
          filename: docs/assets/images/metrics/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 400
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
  projects:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_projects: yes
          plugin_projects_limit: 4
          
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_leetcode: yes
          plugin_leetcode_user: yungshween
          
  starlists:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.starlists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_languages: yes
          
  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_featured: 1
          
  topics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: docs/assets/images/metrics/metrics.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15

  icons:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

  repository-license:
    name: Licenses with open-source ratio graphs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.licenses.ratio.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: nexus-ai
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f pyproject.toml ]] && pip install uv && uv install || true; [[ -f package.json ]] && npm ci || true'
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes

  repository-calendar:
    name: Full-year calendar
    uses: lowlighter/metrics@latest
    with:
      filename: metrics.plugin.isocalendar.fullyear.svg
      token: ${{ secrets.METRICS_TOKEN }}
      base: ""
      plugin_isocalendar: yes
      plugin_isocalendar_duration: full-year
